# Generated by Django 2.2.6 on 2019-10-23 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Energy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='quads',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
